//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBusinessPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORBOOK
    {
        public int AUTHORSetAId { get; set; }
        public int BOOKSetISBN { get; set; }
    
        public virtual AUTHORSet AUTHORSet { get; set; }
        public virtual BOOKSet BOOKSet { get; set; }
    }
}
