//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBusinessPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKSet()
        {
            this.COPYSet = new HashSet<COPYSet>();
            this.AUTHORBOOK = new HashSet<AUTHORBOOK>();
        }
    
        public int ISBN { get; set; }
        public string PublicationYear { get; set; }
        public string Title { get; set; }
        public int Pages { get; set; }
        public string PublicationInfo { get; set; }
        public Nullable<int> CLASSIFICATIONSignId { get; set; }
    
        public virtual CLASSIFICATIONSet CLASSIFICATIONSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COPYSet> COPYSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHORBOOK> AUTHORBOOK { get; set; }
    }
}
