//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBusinessPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORYSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORYSet()
        {
            this.BORROWERSet = new HashSet<BORROWERSet>();
        }
    
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public int Period { get; set; }
        public int PenaltyPerDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BORROWERSet> BORROWERSet { get; set; }
    }
}
