//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBusinessPage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerSideEntities2 : DbContext
    {
        public ServerSideEntities2()
            : base("name=ServerSideEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHORSet> AUTHORSet { get; set; }
        public virtual DbSet<BOOKSet> BOOKSet { get; set; }
        public virtual DbSet<BORROWERSet> BORROWERSet { get; set; }
        public virtual DbSet<BORROWSet> BORROWSet { get; set; }
        public virtual DbSet<CATEGORYSet> CATEGORYSet { get; set; }
        public virtual DbSet<CLASSIFICATIONSet> CLASSIFICATIONSet { get; set; }
        public virtual DbSet<COPYSet> COPYSet { get; set; }
        public virtual DbSet<STATUSSet> STATUSSet { get; set; }
        public virtual DbSet<AUTHORBOOK> AUTHORBOOKSet { get; set; }
    }
}
