//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBusinessPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public short Level { get; set; }
    
        public virtual BORROWER BORROWER { get; set; }
    }
}
