//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBusinessPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COPY()
        {
            this.BORROWs = new HashSet<BORROW>();
        }
    
        public string Barcode { get; set; }
        public string Location { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ISBN { get; set; }
        public string library { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BORROW> BORROWs { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
